### ISSUE TITLE
Menu not displaying submenus properly

### ISSUE THREAD

**Issue by joshbruce** [BrianGilmanGSA/openIAE#29]
```
    - text: 'Visual Style'
      url: 'visual_style'
      class: 'sam_web_standards'
    - text: 'Page Templates'
      url: 'page_templates'
      class: 'sam_web_standards'
      submenu:
        - text: 'Base'
        - url: '#base'
        - class: 'sam_web_standards'
        - text: 'Category Main Page'
        - url: '#category-main-page'
    - text: 'Components'
      url: 'components'
      class: 'sam_web_standards'
      submenu:
        - text: 'Header'
          url: '#header'
```

submenu.submenu - when not the last item in the submenu - results in empty <li> elements.

```
<li>
    <a href="/openIAE/sam_web_standards/visual_style" class="sam_web_standards " target="_self">Visual Style</a>    
</li>

<li>
    <a href="/openIAE/sam_web_standards/page_templates" class="sam_web_standards  usa-current" target="_self">Page Templates</a>
    <ul class="usa-sidenav-sub_list  display-block">

<!-- unexpected output -->
        <li>
            <a href="/openIAE/sam_web_standards/page_templates/" class=" " target="_self">Base</a>

        </li>
        <li>
            <a href="/openIAE/sam_web_standards/page_templates/#base" class=" " target="_self"></a>
        </li>
        <li>
            <a href="/openIAE/sam_web_standards/page_templates/" class="sam_web_standards " target="_self"></a>
        </li>
<!-- unexpected output -->

<!-- unexpected output -->
        <li>
            <a href="/openIAE/sam_web_standards/page_templates/" class=" " target="_self">Category Main Page</a>
        </li>
        <li>
            <a href="/openIAE/sam_web_standards/page_templates/#category-main-page" class=" " target="_self"></a>
        </li>
        <li>
            <a href="/openIAE/sam_web_standards/page_templates/" class="sam_web_standards " target="_self"></a>
        </li>
<!-- unexpected output -->

    </ul>    
</li>
<li>
    <a href="/openIAE/sam_web_standards/components" class="sam_web_standards " target="_self">Components</a>
    <ul class="usa-sidenav-sub_list ">
        <li>
            <a href="/openIAE/sam_web_standards/components/#header" class="sam_web_standards " target="_self">Header</a>
        </li>
```
